### ISSUE TITLE
Is the alarmdecoder website gone?

### ISSUE THREAD

**Issue by gdavids57** [nutechsoftware/alarmdecoder-webapp#100]
When I attempt to connect to https://www.alarmdecoder.com Safari reports the site is unreachable.  Are others having the same experience?

**Comment by f1d094** [comment]
It looks like the SSL certificate expired in march...but the site is still there. Someone should tell him he can get a free cert from letsencrypt that will auto-rotate. ;)

**Comment by gdavids57** [comment]
One can access the site using http (e.g., port 8080) rather than https (e.g., port 443).
