### ISSUE TITLE
ad2usb pointer /dev/ttyUSB.ad2usb stored in database?

### ISSUE THREAD

**Issue by jscherer26** [nutechsoftware/alarmdecoder-webapp#11]
I have two devices plugged into my USB ports. The FTDI USB Serial Device converter (for ad2usb) and a pl2303 converter (for heyu). When the raspberry pi reboots often these ports switch which ttyUSB they are connected to. I have got around this by creating a linux file /etc/udev/rules.d/49-usb-serial.rules. The rules create a pointer to the correct device, so I end up with /dev/ttyUSB.ad2usb and /dev/ttyUSB.heyu that will point to the correct /dev/ttyUSB0 or /dev/ttyUSB1 device.

A while back you made a change so that I could select /dev/ttyUSB.ad2usb in the setup screen for the device. This continues to work. My issue occurs whenever a reboot occurs, it seems that the database stores the /dev/ttyUSB0 or /dev/ttyUSB1 and not my /dev/ttyUSB.ad2usb selection. I'm not certain of this, as I have not inspected the database. If this is the case, is it possible for you to store my selection in the database?

Every once in a while ad2usb reboots on its own and notifies me, not sure why, so I know to go check it, but it would be nice if I didn't have to go through the setup procedure when the USB ports switch.

**Comment by endlesscoil** [comment]
It should store the whole path.  You can confirm that by running this on your pi:

`sqlite3 /opt/alarmdecoder-webapp/instance/db.sqlite "select string_value from settings where name='device_path';"`

You also might check /etc/ser2sock/ser2sock.conf if you're using ser2sock and they got out of sync somehow.
