### ISSUE TITLE
allow http basic authentication in custom notification

### ISSUE THREAD

**Issue by msdowdie** [nutechsoftware/alarmdecoder-webapp#18]
I need to send an HTTP GET or POST to a URL in order to trigger my ISY controller. I can do this easily in a browser. The problem is that the ISY requires login using Basic Authentication. Chrome and at least some other browsers can handle this by including the user and password as part of the request, in the form

http://username:password@192.168.0.120/ ... 20/runThen

Note the username and password at the front. The 192 address and remainder of the URL is what I need to hit on the ISY. I gather that the browser can take that username and password and make it part of the http basic authentication header. There's more on this at

http://forum.universal-devices.com/topi ... t-request/

The colon between username and password may be confusing the app because a port number usually follows a colon.

**Comment by weevis** [comment]
Thanks for the report, I have added support for this in our local branch for testing and deployment - hope to have it out to you soon.

Added form elements to enable authentication, username, and password
Added Authorization header if enabled for GET and POST to URL that require Basic Authentication

**Comment by msdowdie** [comment]
Awesome, comments I read about your terrific support for Alarm Decoder was not exaggerated.

For the record, it is pretty easy to set up a "network resource" on the ISY controller to call into the Alarm Decoder REST API.  I'm using the send keys method to have the ISY arm and disarm the alarm at night and when I depart / arrive.

With a Basic Authentication capability for notifications, it will also be easy to set up an Alarm Decoder web app custom notification to trigger a program on the ISY controller.   I'm planning to use this to turn on all lights when the alarm is triggered or when a zone is faulted in the middle of the night.

Thanks

**Comment by endlesscoil** [comment]
Should be complete as of 0.8.0.
