### ISSUE TITLE
commit 1c5e5c3 possibly broke API call

### ISSUE THREAD

**Issue by aficustree** [nutechsoftware/alarmdecoder-webapp#21]
ref commit 1c5e5c3, this looks to have broken the send api as KEY_S1 isn't defined on the AlarmDecoder object, calling the function results in the following exception

```
AttributeError: type object \'AlarmDecoder\' has no attribute \'KEY_S1\' 
File "/opt/alarmdecoder-webapp/ad2web/api/views.py",\n line 213,\n 
in alarmdecoder_send keys = keys.replace("<S1>", AlarmDecoder.KEY_S1 )
```

**Comment by weevis** [comment]
Update your alarmdecoder library.

**Comment by aficustree** [comment]
Sorry, didn't catch that, 0.12.3 is the latest on pip

**Comment by weevis** [comment]
It is recommended to uninstall the pip version and install the library by hand via github so update notifications will work through the webapp when there is a new release

sudo pip uninstall alarmdecoder
cd /opt
git clone https://github.com/nutechsoftware/alarmdecoder.git
cd alarmdecoder
sudo python setup.py install

**Comment by aficustree** [comment]
cool, thanks, sorry to dime out a commit, just didn't realize the need to manually pull it
