### ISSUE TITLE
Alarm panel doesn't respond after AD2USB firmware upgrade 

### ISSUE THREAD

**Issue by BassmanBiff** [nutechsoftware/alarmdecoder-webapp#23]
Before upgrading the firmware through the webapp's "upload from website" option, the AD2USB worked fine through the webapp. Unfortunately I don't know what the old firmware version was, but I bought the unit recently. Now I can click the buttons in the webapp but nothing happens.

- Incoming messages are still displayed just fine.
- The webapp does update if I use the physical keypad to change things like the chime status.
- Self-diagnostics in the webapp all say they are successful.
- Using "screen /dev/ttyUSB0 115200" , incoming messages look fine (though some are incomplete?). I can reboot using '=' and it says "!Sending.done" for other entries, but the alarm panel doesn't register any changes (for example, the chime status doesn't change after I enter <security code> + 9).
- All physical connections are in place.
- Tried all firmware versions available through the webapp, no change. Currently using 2.2a.8.8. 
- Webapp setup completes successfully using address 18.
- I updated the webapp and libraries through the webapp itself.
- Says some packages are missing in Python? Pip says that most are present. Haven't updated pip, it's at 8.1.1 as it came in the Raspbian image from the website. Python version 2.7.

- System: Raspberry Pi with the image provided on the website. No changes besides expanding the filesystem.
- Device: AD2USB
- Panel, as identified by the webapp: Honeywell Vista 15P
- Panel firmware version, as identified by the webapp: 05.03 04.01

Any help is appreciated!

**Comment by BassmanBiff** [comment]
Sent an email too, ticket number #50491.

**Comment by BassmanBiff** [comment]
Update: Tried to reset the webapp using the following:

'cd /opt/alarmdecoder-webapp/
sudo rm instance/db.sqlite
python manage.py initdb'

Now, the "Get panel info" button works (didn't work before), and setup cannot complete because either the "save config" step times out (thus send and receive time out too) or only "send" times out.

**Comment by endlesscoil** [comment]
Did you get any traction with the support ticket?  

This feels like either a wiring issue or some sort of port conflict.  If you're still having trouble I'd suggest trying to send keys manually via telnet or screen to make sure communication works both ways.  If you're configured to have the device shared on the network you can telnet to port 10000 and watch the communication during the process.  A log of that would be useful in debugging the issue.

You'll also want to make sure that you don't have more than one thing opening the port at the same time, for example: ser2sock & screen.  If they're fighting for the port it will cause odd things to happen with missing or incomplete messages.
