### ISSUE TITLE
Need the ability to restore notification_messages to factory default

### ISSUE THREAD

**Issue by f34rdotcom** [nutechsoftware/alarmdecoder-webapp#33]
https://github.com/nutechsoftware/alarmdecoder-webapp/blob/c856baa2bac15b9b4850266fe864e367fd5ce924/ad2web/notifications/constants.py#L40
If the text of an item is updated it will not be updated in the sqlite3 table notification_messages.
@weevis bug or feature?

**Comment by weevis** [comment]
Those are just the default messages... I'm not sure what you're saying?  If
you update from the webui the database gets changed.  I believe those
defaults are only written on initial setup.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by f34rdotcom** [comment]
If I damage a default record I have no way to restore it short ssh into the box and deleting the table and restarting the system.

Need the ability to restore notification_messages to factory defaults
/settings/notifications/messages

**Comment by f34rdotcom** [comment]
Fix in current PR. Resets notification message formats by adding a version number to the data.
