### ISSUE TITLE
After latest update this AM 

### ISSUE THREAD

**Issue by macbentosh** [nutechsoftware/alarmdecoder-webapp#41]
Loading the web app brings up 
Services starting message. 
Page is titled 503 bad gateway 
Services might still be starting - please wait and try again. If this continues, please let us know on GitHub. You can also email us at Support.

**Comment by f34rdotcom** [comment]
Not sure what version you were on before the update but I believe a version(s) exist that had update issues related to the API. If you look at the logs in /opt/alarmdecoder-webapp/instances/logs/info.log it will show an error in the API or some exception over and over as it restarts. A work around other than updating your full image is to run 'sudo python setup.py install' in /opt/alarmdecoder/

I just uploaded the full image with updated api and webapp on our download page for the Pi.

**Comment by macbentosh** [comment]
o attribute 'on_chime_changed' [in /op
t/alarmdecoder-webapp/ad2web/decoder.py:
549]
Traceback (most recent call last):
  File "/opt/alarmdecoder-webapp/ad2web/
decoder.py", line 535, in run
    self._decoder.open()
  File "/opt/alarmdecoder-webapp/ad2web/
decoder.py", line 293, in open
    self.bind_events()
  File "/opt/alarmdecoder-webapp/ad2web/
decoder.py", line 325, in bind_events
    self.device.on_chime_changed += buil
d_message_handler('chime')
AttributeError: 'AlarmDecoder' object ha
s no attribute 'on_chime_changed'
2018-05-30 17:22:31,026 INFO: Attempting
 to reconnect to the AlarmDecoder [in /o
pt/alarmdecoder-webapp/ad2web/decoder.py
:533]
2018-05-30 17:22:31,068 ERROR: Error in 
DecoderThread: 'AlarmDecoder' object has
 no attribute 'on_chime_changed' [in /op
t/alarmdecoder-webapp/ad2web/decoder.py:
549]
Traceback (most recent call last):
  File "/opt/alarmdecoder-webapp/ad2web/
decoder.py", line 535, in run
    self._decoder.open()
  File "/opt/alarmdecoder-webapp/ad2web/
decoder.py", line 293, in open
    self.bind_events()

**Comment by macbentosh** [comment]
Ram setup.py same issue

**Comment by macbentosh** [comment]
Fixed. Didn’t pull the git
