### ISSUE TITLE
Alarmdecoder Webapp update crashes

### ISSUE THREAD

**Issue by robithomas** [nutechsoftware/alarmdecoder-webapp#42]
I tried to update to 0664184 to 6558799 from the Alarmdecoder Webapp since the webapp showed that my version was 214 commits behind
Webapp stops working and all I get is that service is restarting. 
--

**Comment by f34rdotcom** [comment]
Lots of issues with our early images oil change code. Newer images AFAIK are doing better.

**Comment by WilsonBradley** [comment]
Is there another place to get the latest image your referring to?

I only see and used ;
Download
<http://www.alarmdecoder.com/downloads/pi/alarmdecoder-raspbian-2018-05-29.zip>
2018-05-29
https://www.alarmdecoder.com/wiki/index.php/Raspberry_Pi

Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by f34rdotcom** [comment]
Ya that is the latest release and has both of the latest release of the webapp and api and is what I am shipping on orders currently.
