### ISSUE TITLE
Requirements.txt needs newer version of alarmdecoder

### ISSUE THREAD

**Issue by Rickerdo** [nutechsoftware/alarmdecoder-webapp#44]
I recently upgraded the web app from v0.7.6-0-g82282c8 to v0.8.2-0-g0664184 using git. After the upgrade gunicorn kept logging "AttributeError: 'AlarmDecoder' object has no attribute 'on_ready_changed'". I had version 0.12.3 of alarmdecode installed which did NOT have the "on_ready_changed" class attribute defined. Running "pip install alarmdecoder --upgrade" resolved the issue by upgrading me to alarmdecoder-1.13.4. The requirements.txt file shows "alarmdecoder>=0.9" which should probably read alarmdecoder>=1.13.4 instead.

I'm not sure which version of alarmdecode introduced "on_ready_changed", but it certainly exists in alarmdecoder-1.13.4.

**Comment by WilsonBradley** [comment]
Having same issue.


Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by WilsonBradley** [comment]
Same issue and then get worse with 502 webserver / Services not running
error page and not able to  access anything within anymore.

502 Bad Gateway
Services might still be starting - please wait and try again. If this
continues, please let us know on GitHub. You can also email us at Support.


Sincerely,

Wilson Bradley
Wilsonb@pobox.com

**Comment by f34rdotcom** [comment]
Sorry guys I have been AFK a bit the past few weeks and missed this thread. Will look today and see what is what. If anyone has a system with this issue I can test on I may need it to reproduce the problem.
