### ISSUE TITLE
After updating via webapp - Main , webpage is permantly broke, 505 page not found. This was brought up before with detail and still causing issues.

### ISSUE THREAD

**Issue by WilsonBradley** [nutechsoftware/alarmdecoder-webapp#52]

**Comment by WilsonBradley** [comment]
Only work around so far is to start from scratch again..

**Comment by f34rdotcom** [comment]
Is this effecting the new Raspbian 9 image or just the older image?

**Comment by WilsonBradley** [comment]
Sorry for the late response.. I just recently did an update via Web UI and it DID NOT hose it up.. The latest merges are good.  Thanks.
