### ISSUE TITLE
Failed to install Smartapp

### ISSUE THREAD

**Issue by robithomas** [nutechsoftware/alarmdecoder-webapp#59]
My Alarmdecoder smartapp and devices stopped working last week. 

I reinstalled the Alarmdecoder webapp and firmware (2.2a.8.8) on the Raspberry PI. I have installed the Smartapp (Version 2.0.3) and I tried to install the Alarm Decoder service for my Location.

I get the following errors
d7addcab-9edf-4625-9305-cb40d07db275 10:53:50 PM: error armStaySet: Could not find 'armStay' device.
d7addcab-9edf-4625-9305-cb40d07db275 10:53:50 PM: error armAwaySet: Could not find 'armAway' device.

When I cannot get the Smartthing app to sync with the Alarmdecoder. If I arm using Web panel keyboard or physical keyboard, it is not reflected in the smartapp and vice versa. What changed?

**Comment by f34rdotcom** [comment]
This is all resolved AFAIK on the dev branch. I will merge this to master soon so far my own testing on dev has had no issues. We no longer use the "SmartThings" notification feature of the AD2 Web app. It now uses UPNP. I just push a bunch of changes to dev over the weekend and so far everything is stable for me.
