### ISSUE TITLE
Googletalk notification form is not populating "notify on.."  fields

### ISSUE THREAD

**Issue by ss2400** [nutechsoftware/alarmdecoder-webapp#6]
When launching the googletalk notification setup, the form is not retaining or displaying any "notify on.." selections.

notification/forms.py
class GoogleTalkNotificationForm(EditNotificationForm):
    def populate_settings(self, settings, id=None):
    def populate_from_settings(self, id):

both missing "EditNotificationForm.populate_from_settings(self, id)" ?

**Comment by weevis** [comment]
That is correct - this is fixed in our local development branch (along with the addition of about 6 notification types such as Twilio, Pushover, NotifyMyAndroid etc) - we hope to have this pushed up for use soon.

Thanks for the report, though!
