### ISSUE TITLE
Not detecting need to update web after udpate api and restarting.

### ISSUE THREAD

**Issue by f34rdotcom** [nutechsoftware/alarmdecoder-webapp#61]
Software updates alert only shows if the API is out of date. It does not seem to show if the web portion is behind? I used a stock image and after setup applied the patches to the API and clicked the restart leaving the WEB portion behind and needing update. After reconnecting the update screen was gone and reported no more updates were needed. Console access shows the WEB is still behind master.

**Comment by f34rdotcom** [comment]
Meh. ok after a few minutes it showed up again that updates were avail. The /update/ screen should have detected it and not kept showing all was good. I presume it does not check until N number of seconds after startup but it would be best if when this screen is rendered it does an immediate check?

**Comment by weevis** [comment]
The update check process is in a separate thread, that is likely why you
are seeing discrepancies

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*
