### ISSUE TITLE
Basic authentication "Invalid header value 'Basic T...=\n'

### ISSUE THREAD

**Issue by stevemha** [nutechsoftware/alarmdecoder-webapp#63]
Regarding line 1049 of alarmdecoder-webapp/ad2web/notifications/types.py:
auth_string = base64.encodestring(auth_string)
Should base64.encodestring be changed to base64.b64encode ?

Reason:  In using WebApp for a custom notification, I receive the following error message:
"Error sending test notification: Invalid header value 'Basic Y...w==\n'".
[Note that I inserted ... above is to avoid revealing my authorization credentials.]
A blog unrelated to AlarmDecoder identifies the following cause for a similar error ("ValueError: Invalid header value 'Basic T...4=\n'"):
"You can't have a new line character \n at the end of your header. Instead of using base64.encodestring, use base64.b64encode."
(see https://stackoverflow.com/questions/39874351/basic-authentication-error-with-urllib2-since-python-2-7-update )
Various sites claim that base64.encodestring "returns a string containing one or more lines of base64-encoded data always including an extra trailing newline (‘\n’)".
This newline character might be the cause of the error message that I receive.

FYI, I receive this error message when using the 2018-10-14 Raspbian Stretch image from	https://www.alarmdecoder.com/wiki/index.php/Raspberry_Pi on a Raspberry Pi3B+.  I also updated WebApp and received the same error message.  I do NOT receive that error message when using the 2018-05-29 Raspbian Jessie 8.0 image from the same website.

Thanks!

**Comment by f34rdotcom** [comment]
Dho.. Just saw this now. Ya that is exactly what was wrong. It was the incorrect API call. I just pushed the fix.
