### ISSUE TITLE
502 Bad Gateway in browser- (tried different devices)

### ISSUE THREAD

**Issue by WilsonBradley** [nutechsoftware/alarmdecoder-webapp#7]
Finally got communication working good with Alarmdecoder on Raspberry and DSC alarm. :D
Figured out through trial and error, and support how to get the correct settings done on Windows PC AlarmDecoder Keypad app and the webbapp (via browser)

Got most working , however for some reason the AlarmDecoder WebApp Keypad stopped working. :cry:
Now when trying to bring it up in a browser, I get 502 Bad Gateway , error.

    "Services might still be starting - please wait and try again. If this continues, please let us know on GitHub. You can also email us at Support."

I tried restarting the Raspberry Pi- & manually restarting the services (nginx & Gunicorn) that seem to restart properly. But still get 502 error.
Restated services without a problem. (Maybe there is another service I am missing)
​pi@alarmdecoder /opt/alarmdecoder-webapp $ sudo service nginx restart
Restarting nginx: nginx.
pi@alarmdecoder /opt/alarmdecoder-webapp $ sudo service gunicorn restart
[ ok ] Stopping Gunicorn workers: [alarmdecoder].
[ ok ] Starting Gunicorn workers: [alarmdecoder].

Communication is good because I can communicate with Windows AlarmDecoder app.
I tried manually installing the webapp from github, and still same issue.

**Comment by weevis** [comment]
As we went over on the support ticket you created - this has to do with the specific version of pip.  We currently only support up to version 6.1.1 - thanks.

**Comment by BassmanBiff** [comment]
Hey, I have this same issue - since I can't see the support ticket, can you post the solution here?
