### ISSUE TITLE
Swagger page does not work with SSL

### ISSUE THREAD

**Issue by manonstreet** [nutechsoftware/alarmdecoder-webapp#79]
When SSL is enabled and the swagger page is visited by navigating to:
https://alarmdecoder.local/static/swagger/index.html (by following the link from /api)

There are two issues:
1) The webapp does not detect that SSL is in use and populates wrong URL for the alarmdecoder.json
`http://alarmdecoder.local:5000/static/alarmdecoder.json` instead of `https://alarmdecoder.local/static/alarmdecoder.json`

2) If the endpoint is manually corrected, the swagger page is shown however the REST APIs cannot be invoked.  The Request URL is hard coded to utilize `http://alarmdecoder.local:5000/api/v1/alarmdecoder` instead of using the server information relative to the supplied json.

**Comment by f34rdotcom** [comment]
Improved in a0b784f.

**Comment by manonstreet** [comment]
Thanks - but when is this going to be merged to master?
