### ISSUE TITLE
UPNPPushNotification error

### ISSUE THREAD

**Issue by jscongdon** [nutechsoftware/alarmdecoder-webapp#80]
ERROR: Exception in notification UPNPPushNotification.send(): StandardError("BadStatusLine('No status line received - the server has closed the connection',) line 657",) line 544 [in /opt/alarmdecoder-webapp/ad2web/decoder.py:459]

**Comment by f34rdotcom** [comment]
Well I spent the day at home trying everything I could think of to fix my home ST setup and nothing worked. I tried rebooting the ST hub and letting AD2 Web services be ready to go. I tried rebooting and having the AD2 Web services not running till after a few minutes to let the hub settle before "local" requests were pushed to the HUB. Nothing worked. I added a hack to the code to force a resubscribe of "local" notifications for the UPNP notify requests. Nope. No messages sent to the HUB would trigger a log so AFAIK the connection between the local services daemon on the ST hub was not working. It would accept TCP requests and complete the SYN/ACK and get posted data and then just stall out and finally disconnect after ~30 seconds. 

Finally I moved on to working on my home core server and other projects. This morning I wake up and disarm with the ST app and it magically updates instantly :(

Crazy Sauce.

**Comment by jscongdon** [comment]
Still a no go here.
I am watching the traffic coming from my AlarmDecoder device... and am not seeing anything come from it at the time the notification is erroring out.

**Comment by f34rdotcom** [comment]
Ok thanks for the update. I did get a reply from ST support but no answers
just they are looking. By now I would have expected your issues to be
resolved. It may be best now for you to submit a ticket as well to ST.

How much pain is it for you to remove all your AD2 ST devices and start
from scratch running the AD2ST install.
It may be that for this to be fixed all existing AD2 active code needs to
be off and all the services for AD2 removed from the Location. Once it is
all gone then running the install process. The code can stay but be sure
its updated before you start the update again.

Anyway I can not count how many times I did this process during debugging /
testing and I can not say it will help but it is one thing to try that we
have not tried yet.

If you want I can do this with you remotely to be sure its all clear before
we add the ST devices back.

Best
SM


[image: image.png]

**Comment by jscongdon** [comment]
I may have to do something.
I lost the UPNP functionality sometime after applying some updates (between the ST device, webapp, and library). Unfortunately, I did not log the version I was at when I did it.
I've lost all semi-immediate triggers from the system - and until you do, you don't realize how much you depend on them.

**Comment by f34rdotcom** [comment]
If you want me to be a wingman etc we can remove all and start from scratch
I'm ST graph pages.

So far my house has been stable.

**Comment by jscongdon** [comment]
At this point, I'm pretty frustrated with it and am walking away from it for a little bit before I literally throw it out the window. I just went through and re-built everything about a couple months ago, when an update borked the system.
Because the app-only offers 20 zones and I have more - I end up having to remember/find what I need to change to make the allowance for my system. And then there's the mapping of my zone numbers the zone numbers in the app... it just takes time. And then once that's all set up, I have to update webCore.
And, I have no clue what "I'm ST graph pages" means.

**Comment by f34rdotcom** [comment]
Ya I had similar frustrations on my setup at home. I did add for easy
adding more zones and again when you want I will help. I ment "in
smartthings graph pages"

Whenever you want call and I will help.

Best
Sean M

**Comment by WilsonBradley** [comment]
All this traffic is concerning. I'm usually the first in line to beta test,
but it sounds unstable or not coordinated with the constant bugs popping up.
Just to make sure, these bugs relate more to the Dev branch, correct?
When I was down a year ago because of the web server having constant
strange issues, I stopped using Dev.
Sticking with Master.

Also, stupid noob question , but how do I add certificate to approved? To
whitelist Alarmdecoder in browsers?

Sincerely,

Wilson Bradley
Wilsonb@pobox.com
▬▬▬▬▬▬▬▬▬▬▬ஜ۩☆۩ஜ▬▬▬▬▬▬▬▬▬▬
[image: 🗽]Make 𝐀𝐌𝐄𝐑𝐈𝐂𝐀 𝐆𝐑𝐄𝐀𝐓[image: 🗽]

▬▬▬▬▬▬▬▬▬▬▬ஜ۩☆۩ஜ▬▬▬▬▬▬▬▬▬▬

**Comment by f34rdotcom** [comment]
The updates I have made in the past 6 months were painful but necessary to
fix a pile of issues and missing features.

The stability issues inside of the smartthings cloud is out of my control.

I have had no such stability issues with Hubitat so far but I still prefer
the ST classic app so l am sticking with ST for now at home. If ST hub does
go poof again I may office space it.

 So far I am very happy with the final results at my house and have no
current plans for any major updates.

The latest raspbian Buster image I did a few weeks back includes a small
change in how the SSL key is generated to help with browser
compatibility issues. It was one of the many issues on the list. I added
the trusted name alarmdecoder.local. It is still a self signed key. No one
has provided feedback if it helped yet.

I believe raspbian buster will get 5 years of security and patch updates
before it is retired. The original AD2 raspian images no longer can be
updated.

Sorry for the bumpy ride and I will do my best to keep it stable moving
forward  and hopefully smartthings fixes its issues.

Best
Sean M

**Comment by WilsonBradley** [comment]
Thanks for being upfront and everything you do..
It's appreciated.

Sincerely,

Wilson Bradley
Wilsonb@pobox.com
▬▬▬▬▬▬▬▬▬▬▬ஜ۩☆۩ஜ▬▬▬▬▬▬▬▬▬▬
[image: 🗽]Make 𝐀𝐌𝐄𝐑𝐈𝐂𝐀 𝐆𝐑𝐄𝐀𝐓[image: 🗽]

▬▬▬▬▬▬▬▬▬▬▬ஜ۩☆۩ஜ▬▬▬▬▬▬▬▬▬▬

**Comment by jscongdon** [comment]
Spent the better part of 4 hours just removing everything.
Downloaded and wrote the PiBakery image.
Updated wpa_supplicant.conf to connect to my network
Went through dummy setup of WebApp... then imported my settings.
Updated the WebApp
Updated the Library
From the repo:
Reinstalled the AlarmDecoder Service Smart App
Reinstalled most of the device handlers (Virtual Motion sensor is not installing due to an error)
Updated the AlarmDecoder Service to allow for the number of zones I have
Updated the Network Appliance device handler to allow for the number of zones I have
Setup the AlarmDecoder UI and mapped the UI sensors to my sensors.
...
ERROR: Exception in notification UPNPPushNotification.send(): StandardError("BadStatusLine('No status line received - the server has closed the connection',) line 657",) line 544 [in /opt/alarmdecoder-webapp/ad2web/decoder.py:459]

**Comment by f34rdotcom** [comment]
Home worked when I went to bed not this AM. Did some digging and found this. Looks like not having a limiter on threads will be a good one to fix and soon. Still no idea other than my hub is pissed why it would start stalling out my connections. @jscongdon yes that is the exact error I would expect from the latest code for the hub ignoring the UPNP push request. So ya that is the issue 100% you have everything updated and the only thing that changed was the error is now a little more clear :(

```2019-09-06 18:19:45,154 INFO: Background notification functions running 1109. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:19:48,362 INFO: Background notification function UPNPPushNotification._send_notify_event() starting. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:150]
2019-09-06 18:19:48,365 INFO: Background notification function UPNPPushNotification._send_notify_event() starting. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:150]
2019-09-06 18:19:48,374 INFO: Event: 0041594:0:1:0:0:0:0 [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:522]
2019-09-06 18:19:50,208 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:19:55,282 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:20:00,312 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:20:05,358 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:20:10,387 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:20:15,453 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:20:20,482 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
2019-09-06 18:20:25,513 INFO: Background notification functions running 1111. [in /opt/alarmdecoder-webapp/ad2web/notifications/types.py:439]
```

**Comment by f34rdotcom** [comment]
Interesting. So each new event the AD2PI Pushed a notification and each time the ST HUB just replied with an ACK and then nothing... This would be a very odd case to capture but I will look at the code and see what can be done. It already handles a normal timeout but this is not a normal timeout case. 

![image](https://user-images.githubusercontent.com/2042644/64451876-fa55a000-d099-11e9-82aa-efa9bb6dc41b.png)

**Comment by f34rdotcom** [comment]
Meh.. everything was fine after I restarted gunicorn... I will put this as a high priority issue to at least be sure our worker can handle all the crazy sauce ST gives us.

**Comment by f34rdotcom** [comment]
> Meh.. everything was fine after I restarted gunicorn... I will put this as a high priority issue to at least be sure our worker can handle all the crazy sauce ST gives us.

Ok. further reading looks like the failure was on my end. The final packet and close would have come from me and I never sent it.

**Comment by jscongdon** [comment]
So... I've been looking over every little thing to see if I could figure anything out.
And... in the Smartthings graph.api > My Hubs > View Utilities, I sent the 'Reboot Hub' command.
uPNP is working for me now. WTF!

Though, now when I go to Notifications in the WebApp, select the uPNP, select Next and Save & Test... the web app gives a positive response that the test was successful.
But in the graph.api I am seeing this:

>9:03:21 PM: error java.lang.NumberFormatException: For input string: "" @line 420 (parse_xml)
>9:03:21 PM: trace --- parse_xml
>9:03:21 PM: info --- parse: mac: XXXXXXXXXXXX requestId: 000000000000

**Comment by jscongdon** [comment]
It appears that xmlResult is being seen as
>TestingTest NotificationFalseFalseFalseFalseFalseTrueFalseTrueFalseFalseFalseADEMCOFalseFalse[10000001000000003A--],008,[f70200051008001c08020000000000],"****DISARMED**** Ready to Arm "
So that could explain why it's erroring.

Also, I was trying to issue the following from the AlarmDecoder Pi:
`curl -H "Content-Type: application/json" -X POST -d '{"message":"Hi, this is a test from AlarmDecoder network device"}' http://192.168.1.202:39500`
And wasn't seeing anything, until added a log.trace for `result`

**Comment by f34rdotcom** [comment]
> So... I've been looking over every little thing to see if I could figure anything out.
> And... in the Smartthings graph.api > My Hubs > View Utilities, I sent the 'Reboot Hub' command.
> uPNP is working for me now. WTF!
> 
> Though, now when I go to Notifications in the WebApp, select the uPNP, select Next and Save & Test... the web app gives a positive response that the test was successful.
> But in the graph.api I am seeing this:
> 
> > 9:03:21 PM: error java.lang.NumberFormatException: For input string: "" @line 420 (parse_xml)
> > 9:03:21 PM: trace --- parse_xml
> > 9:03:21 PM: info --- parse: mac: XXXXXXXXXXXX requestId: 000000000000

The test for UPNP is fake. It cant be tested unless we startup some client so for now its just a dummy test and returns passing.

curl to the "local" services on the ST hub on port 39500 is a good test but be sure not to upset the ST hub. If you send it anything it does not expect I have seen it lockup and not process any further requests until the ST hub is rebooted.

**Comment by f34rdotcom** [comment]
No idea why that line would fail. I would have liked to see what was posted in. Probably not a correctly formatted XML notification event? In any case it shows it did correctly receive it so that is good!

If zones update in the ST app but the "AlarmDecoder UI" smartthings app does not refresh just this screen. Hmm. first guess kill and restart the app on the phone to confirm this is not just a bug in the app.

https://github.com/nutechsoftware/alarmdecoder-smartthings/blob/1a482361dde08dfa18db6fca777b330c67ec42d3/devicetypes/alarmdecoder/alarmdecoder-network-appliance.src/alarmdecoder-network-appliance.groovy#L420

**Comment by jscongdon** [comment]
Well, my line 420 is different.
I have 27 zones, so I needed to expand the preferences section to reflect that.
My line 420 is equivalent to the native:
https://github.com/nutechsoftware/alarmdecoder-smartthings/blob/1a482361dde08dfa18db6fca777b330c67ec42d3/devicetypes/alarmdecoder/alarmdecoder-network-appliance.src/alarmdecoder-network-appliance.groovy#L413

I think that you are right, that it's not seeing correctly formatted XML.  The
> TestingTest NotificationFalseFalseFalseFalseFalseTrueFalseTrueFalseFalseFalseADEMCOFalseFalse[10000001000000003A--],008,[f70200051008001c08020000000000],"DISARMED Ready to Arm "

is what xmlResult is coming out to at this point:
`def xmlResult = new XmlSlurper().parseText(body)`
Line 410
