### ISSUE TITLE
AlarmDecoder Address Mask is 0 (not ffffffff)

### ISSUE THREAD

**Issue by jscherer26** [nutechsoftware/alarmdecoder-webapp#9]
I reinstalled and imported my settings using a raspberry pi with a ad2usb plugged into /dev/ttyUSB1 and all is good accept the AlarmDecoder Address Mask is 0 (not ffffffff). I don't think it was directly related to the import, as I have seen this change to zero on occasion when in setup, but haven't been able to identify the behavior that causes it. 

I have two usb devices connected to my pi, one on /dev/ttyUSB0 and the other on /dev/ttyUSB1, and the assignment isn't consistent from one reboot to another. So the ad2usb sometimes is /dev/ttyUSB0 and other times /dev/ttyUSB1. 

It does not seem to be an issue with Setup -> AlarmDecoder Settings -> Web Address Mask. So there likely is a condition where these are handled differently and AlarmDecoder Address Mask is either never assigned or being assigned to something that doesn't exist? That is just a guess on my part. A further guess would be that it may have to do with the system thinking the ad2usb is located on a port being used for something else.

**Comment by jscherer26** [comment]
So of course, immediately after I submitted the above issue, I found one way to replicate it. If my path is set to the wrong USB device (not the ad2usb) and I am on the Setup -> Alarmdecoder Settings page and I click log out (not finishing setup) immediately the Alarmdecoder Address Mask changes to 0. If I do the same with my path having been set to the correct USB device, the Alarmdecoder Address Mask stays ffffffff. I am not allowed to log out in either case, as I first need to complete the setup.

**Comment by endlesscoil** [comment]
Thanks for the report and steps to replicate.  I'll take a look and see if
I can track it down.

**Comment by endlesscoil** [comment]
Fixed in the AlarmDecoder library: [ecd3904](https://github.com/nutechsoftware/alarmdecoder/commit/ecd390487c292d3d4497872667c1f7c577700c7d)

Latest revision of the webapp that was just pushed will update the library as well as the app itself.

**Comment by jscherer26** [comment]
Your fix was:

self.address_mask = 0xFFFFFFF (7 f's which becomes 0x0FFFFFFF I believe)

did you want it to be

self.address_mask = 0xFFFFFFFF (8 f's)

**Comment by endlesscoil** [comment]
Good catch.  Thanks James.  Typo is fixed in [9ab05d9](https://github.com/nutechsoftware/alarmdecoder/commit/9ab05d95b3b082dcdeff4934a65d37f89a34b190).
